---
name: CI
on:
  push:
    branches: [ main ]
jobs:
  build-glaber:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build glaber
        run: |
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install -y packer
          export GLABER_VERSION="3.4.1"
          export CI_REGISTRY_USER="${{ github.actor }}"
          export REPO_DIR="repo"
          export CI_REGISTRY="ghcr.io"
          export CI_REGISTRY_IMAGE="ghcr.io/${{ github.repository }}"
          cd build/appliance/build/docker
          packer init .
          packer validate .
          export DOCKER_PASSWORD=${{ secrets.GITHUB_TOKEN }}
          packer build -color=false -timestamp-ui -warn-on-undeclared-var .