---
name: CI
on:
  push:
    branches: [ main ]
jobs:
  build-glaber:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: "1.8.5"
      - name: Build glaber
        run: |
          export GLABER_VERSION="3.4.1"
          export CI_REGISTRY_USER="${{ github.actor }}"
          export REPO_DIR="repo"
          export CI_REGISTRY="ghcr.io"
          export CI_REGISTRY_IMAGE="ghcr.io/${{ github.repository }}"
          cd build/appliance/build/docker
          packer init .
          packer validate .
          export DOCKER_PASSWORD=${{ secrets.GITHUB_TOKEN }}
          packer build -color=false -timestamp-ui -warn-on-undeclared-var .