---
name: CI
on:
  push:
    branches: [ main ]
jobs:
  build-glaber:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bakaut/builder/builder:glaber-debian-bullseye-0.0.1-23
      volumes: ${{ github.workspace }}:/opt/glaber
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build glaber
        run: |
          cd /opt/glaber
          ls
          pwd
          export GLABER_VERSION=$(cat include/version.h | grep GLABER_VERSION | tr -dc 0-9.)
          ./bootstrap.sh
          ./configure
          make dbschema gettext
          autoreconf -fvi
          cp -r build/${OS}/${OS_VER}/ debian
          sed -i "1 s/(.*+/(1:$GLABER_VERSION-${CI_COMMIT_SHORT_SHA}+/g" debian/changelog
          head -n 5 debian/changelog
          dpkg-buildpackage -b --no-sign